name: leancode_forms_example
description: A new Flutter project.
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc_presentation: ^0.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.1
  leancode_forms:
    path: ..
  rxdart: ^0.28.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0

flutter:
  uses-material-design: true
