name: leancode_forms_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.1
  leancode_forms:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0

flutter:
  uses-material-design: true
