version: 2
updates:
  - package-ecosystem: pub
    directory: /
    groups:
      all_dependencies:
        patterns:
          - "*"
    schedule:
      interval: weekly
    versioning-strategy: widen