name: leancode_forms
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  bloc_dispose_scope: ^3.0.0
  collection: ^1.17.1
  dispose_scope: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^6.0.0


flutter: